import{a as q,S as B,i}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const $="55697011-aeb065fcda8ad69c490025643",E="https://pixabay.com/api/";async function m(s,t){return(await q.get(E,{params:{key:$,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more"),M=new B(".gallery a",{captionsData:"alt",captionDelay:250});function p(s){const t=s.map(({webformatURL:o,largeImageURL:c,tags:e,likes:r,views:n,comments:S,downloads:P})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${o}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r}</p>
          <p><b>Views</b> ${n}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${P}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",t),M.refresh()}function O(){y.innerHTML=""}function b(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function w(){g.classList.remove("is-hidden")}function l(){g.classList.add("is-hidden")}const f=document.querySelector(".form"),x=document.querySelector(".load-more");let d="",a=1,u=0;const v=15;f.addEventListener("submit",async s=>{s.preventDefault();const t=f.elements["search-text"].value.trim();if(t){d=t,a=1,O(),l(),b();try{const o=await m(d,a);if(u=o.totalHits,o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}p(o.hits),a*v>=u?(l(),i.info({message:"We're sorry, but you've reached the end of search results."})):w()}catch{i.error({message:"Something went wrong. Please try again!"})}finally{L()}}});x.addEventListener("click",async()=>{a+=1,b(),l();try{const s=await m(d,a);p(s.hits);const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}a*v>=u?(l(),i.info({message:"We're sorry, but you've reached the end of search results."})):w()}catch{i.error({message:"Something went wrong. Please try again!"})}finally{L()}});
//# sourceMappingURL=index.js.map
